version: "3"

services:
  auth:
    build: "./auth"
    ports:
      - "3000:3000"
  membership:
    build: "./membership"
    ports:
      - "3001:3001"
  product:
    build: "./product"
    ports:
      - "3002:3002"    
